name: Perfiles
type: model
class: App\Profile
admin: true
icon: users
options:
  storage: perfil
fields:
  id:
    label: ID
    type: id
    list: false
  name:
    label: Nombre
    type: text
    required: true
  is_admin:
    label: Administrador
    type: checkbox
    width: 6
  has_panel:
    label: Panel
    type: checkbox
    width: 6
  created_at:
    label: Creado
    type: timestamp
    mobile: false
